#!/bin/bash
# Ignore SC2086 as per instructions
# shellcheck disable=SC2086

get_subdomain_info() {
    local sub=$1
    local dom=$2
    local result

    result=$(dig ${sub}.${dom} +short | awk 'NR==1 {ip=$1} END {print ip}')
    record_type="A"

    if [ -n "$result" ]; then
        echo "The subdomain ${sub} is a ${record_type} record and points to ${result}"
    fi
}

domain=$1
subdomain=$2

if [ -n "$domain" ] && [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info $sub $domain
    done
elif [ -n "$domain" ] && [ -n "$subdomain" ]; then
    get_subdomain_info $subdomain $domain
fi
