#!/usr/bin/env bash
# this is a script to scp a file to a remote server

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

scp  -o  "$FILE_PATH" "$USERNAME@$SERVER_IP:~/" -i "$SSH_KEY_PATH" 

