#!/usr/bin/env bash
# A script that configures a new Ubuntu machine

# sudo apt-get update
# sudo apt-get install -y nginx

# echo "Hello World!" | sudo tee /var/www/html/index.html
# string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/www.blog.ehoneahobed.com permanent;"
# sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# sudo service nginx restart

INDEX_COPY="Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
